name: fin_tech
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# For Android
version: 1.0.0+1

environment:
  sdk: ^3.5.0

#  Current Flutter Version 3.24.2

dependencies:
  flutter:
    sdk: flutter
#    View
  cupertino_icons: ^1.0.2

#  font_awesome_flutter: ^10.5.0
  carousel_slider: ^5.0.0
  local_auth: ^2.3.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  logger: ^2.3.0
  intl: ^0.19.0
  fluttertoast: ^8.2.8
  google_fonts: ^6.2.1
  get_storage: ^2.1.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  screen_protector: ^1.4.2+1
  flutter_animate: ^4.5.0
  url_launcher: ^6.3.0
  share_plus: ^10.0.2
  gradient_borders: ^1.0.0
  convert: ^3.1.1
  image_picker: ^1.1.2
  collection: ^1.19.0
  equatable: ^2.0.5
  flutter_pdfview: ^1.3.2
  swipe_to: ^1.0.6
  socket_io_client: ^2.0.3+1
  scrollable_positioned_list: ^0.3.8
  path_provider: ^2.1.4
  restart_app: ^1.3.1




# firebase Notifications
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.4
#  cloud_firestore: ^4.15.10
  permission_handler: ^11.3.1
  google_sign_in: ^6.2.1
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.5.1


  #  firebase_analytics: ^10.7.4

#
#  Block Chain / Web3
  web3dart: ^2.7.3
  bip39: ^1.0.6
  bip32: ^2.0.0
  hex: ^0.2.0

  animated_text_kit: ^4.2.2

# Network
  http: ^1.2.1

#  State Management
  provider:
  get:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
# Deep Links

dependency_overrides:
  collection:
  web:


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  change_app_package_name:
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
flutter_launcher_icons:

  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/launcher_icon.png"
  min_sdk_android: 21
#  adaptive_icon_background: "assets/launcher_icon.png"
#  adaptive_icon_foreground: "assets/launcher_icon.png"

flutter:

  uses-material-design: true

  # To add assets.dart to your application, add an assets.dart section, like this:
  assets:
    - assets/
    - assets/create wallet/




